/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.87
 * Generated at: 2024-07-23 05:30:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class joinform_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>회원가입</title>\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\">\r\n");
      out.write("    <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("	  <script src=\"https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("	\r\n");
      out.write("    <style>\r\n");
      out.write("        .content {\r\n");
      out.write("            width: 50%;\r\n");
      out.write("            margin: auto;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .innerOuter {\r\n");
      out.write("            border: 1px solid lightgray;\r\n");
      out.write("            width: 80%;\r\n");
      out.write("            margin: auto;\r\n");
      out.write("            padding: 5% 10%;\r\n");
      out.write("            background-color: white;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #userId, #userPwd, #checkPwd, #userName, #tel,\r\n");
      out.write("         #email, #postcode, #address1, #address2, #nickName {\r\n");
      out.write("            width: 400px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-group.rel {\r\n");
      out.write("            width: 500px;\r\n");
      out.write("            margin: 0px auto;\r\n");
      out.write("            position: relative !important;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-control {\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("            margin-bottom: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btns {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .joinbtn, .resetbtn {\r\n");
      out.write("            display: block;\r\n");
      out.write("            width: 400px;\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("            margin-bottom: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #checkId {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            width: 95px;\r\n");
      out.write("            height: 40px !important;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            left: 455px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #checkNickName {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            width: 95px;\r\n");
      out.write("            height: 40px !important;\r\n");
      out.write("            margin-left: 10px;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            left: 445px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #findaddr {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            width: 95px;\r\n");
      out.write("            height: 40px !important;\r\n");
      out.write("            margin-left: 10px;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            left: 445px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        #checkEmail{\r\n");
      out.write("        	position: absolute;\r\n");
      out.write("            width: 95px;\r\n");
      out.write("            height: 40px !important;\r\n");
      out.write("            margin-left: 10px;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            left: 445px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("           #si{\r\n");
      out.write("            width : 400px\r\n");
      out.write("           }\r\n");
      out.write("        \r\n");
      out.write("           #gu, #dong{\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("          	width : 195px;\r\n");
      out.write("          	margin-right : 5px; \r\n");
      out.write("          }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"content\">\r\n");
      out.write("        <br><br>\r\n");
      out.write("        <div class=\"innerOuter\">\r\n");
      out.write("            <h2>회원가입</h2>\r\n");
      out.write("            <br>\r\n");
      out.write("\r\n");
      out.write("            <form action=\"member/join\" method=\"post\" onsubmit=\"return ccc();\">\r\n");
      out.write("                <div class=\"form-group rel\">\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" id=\"userId\" placeholder=\"아이디\" name=\"userId\" >\r\n");
      out.write("                    <button type=\"button\" class=\"btn btn-outline-secondary\" id=\"checkId\">중복체크</button>\r\n");
      out.write("                </div>\r\n");
      out.write("				\r\n");
      out.write("				<div class=\"form-group\">\r\n");
      out.write("                    <input type=\"password\" class=\"form-control\" id=\"userPwd\" name=\"userPwd\"  placeholder=\"비밀번호\" name=\"\" >\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <input type=\"password\" class=\"form-control\" id=\"checkPwd\" placeholder=\"비밀번호확인\" >\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"pwdError\" style=\"color: red; display: none;\"></div>\r\n");
      out.write("                <!-- 비밀번호 확일 일치여부  -->\r\n");
      out.write("				<script>\r\n");
      out.write("				let pwOk ='N'\r\n");
      out.write("				$(()=>{\r\n");
      out.write("					const $checkPwd = $('#checkPwd');\r\n");
      out.write("					const $userPwd = $('#userPwd');\r\n");
      out.write("				    const $pwdError = $('#pwdError');	\r\n");
      out.write("					$checkPwd.blur( () => {\r\n");
      out.write("						if($checkPwd.val() != $userPwd.val() ){\r\n");
      out.write("							$pwdError.text(\"비밀번호확인이 일치하지 않습니다.\").show();\r\n");
      out.write("							pwOk ='N'\r\n");
      out.write("						}else{\r\n");
      out.write("							$pwdError.hide();\r\n");
      out.write("							 pwOk ='Y'\r\n");
      out.write("						}\r\n");
      out.write("					});\r\n");
      out.write("				});\r\n");
      out.write("				\r\n");
      out.write("				</script>\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" id=\"userName\" placeholder=\"이름\" name=\"userName\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"nameError\" style=\"color: red; display: none;\"></div>\r\n");
      out.write("                <!-- 이름 정규식패턴   -->\r\n");
      out.write("				<script>\r\n");
      out.write("				let nameOk='N'\r\n");
      out.write("				$(()=>{\r\n");
      out.write("					const $userName =$('#userName');\r\n");
      out.write("					const $pattern = /^[가-힣]{2,10}$/;\r\n");
      out.write("					const $nameError =$('#nameError');\r\n");
      out.write("					$userName.blur(() => {\r\n");
      out.write("						if(!$pattern.test($userName.val())){\r\n");
      out.write("							$nameError.html(\"이름을 한글 2~10글자로 작성해주세요\").show();\r\n");
      out.write("						}else{\r\n");
      out.write("							$nameError.hide();\r\n");
      out.write("							 nameOk='Y'\r\n");
      out.write("						}\r\n");
      out.write("					});\r\n");
      out.write("					\r\n");
      out.write("				});\r\n");
      out.write("				\r\n");
      out.write("				</script>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group rel\">\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" id=\"nickName\" placeholder=\"닉네임\" name=\"nickname\" >\r\n");
      out.write("                    <button class=\"btn btn-outline-secondary\" type=\"button\" id=\"checkNickName\">중복체크</button>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group rel\">\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" id=\"email\" placeholder=\"이메일\" name=\"email\">\r\n");
      out.write("                    <button class=\"btn btn-outline-secondary\" type=\"button\" id=\"checkEmail\" hidden>메일인증</button>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <input type=\"tel\" class=\"form-control\" id=\"tel\" placeholder=\"연락처\" name=\"tel\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"telError\" style=\"color: red; display: none;\"></div>\r\n");
      out.write("                <script>\r\n");
      out.write("                let telOk='N'\r\n");
      out.write("                $(()=>{\r\n");
      out.write("                	const $tel =$('#tel');\r\n");
      out.write("                	const $pattern =/^(?=.{12,13}$)01[016789]-\\d{3,4}-\\d{4}$/;\r\n");
      out.write("                	const $telError = $('#telError');\r\n");
      out.write("                	$tel.blur(()=>{\r\n");
      out.write("                		if(!$pattern.test($tel.val())){\r\n");
      out.write("                			$telError.html(\"핸드폰번호 양식에 어긋납니다<br>(-를 포함한 12~13자리로 입력해주세요)\").show();\r\n");
      out.write("                			telOk='N'\r\n");
      out.write("                		}else{\r\n");
      out.write("                			$telError.hide();\r\n");
      out.write("                			 telOk='Y'\r\n");
      out.write("                		}\r\n");
      out.write("                	});\r\n");
      out.write("                });\r\n");
      out.write("                </script>\r\n");
      out.write("                \r\n");
      out.write("                <!-- 시 구 동 정보가 담긴 selectbox  -->\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <select class=\"form-control \" id=\"si\">\r\n");
      out.write("                        <option value=\"\">관심지역 선택</option>\r\n");
      out.write("                        <option value=\"1\">서울특별시</option>\r\n");
      out.write("                        <option value=\"2\">인천광역시</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                    <select class=\"form-control \" id=\"gu\" disabled>\r\n");
      out.write("                        <option value=\"\">구 선택</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                    <select class=\"form-control \" id=\"dong\" name=\"villageCode\" disabled>\r\n");
      out.write("                        <option value=\"\">동 선택</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                </div>\r\n");
      out.write("          \r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("				<script>\r\n");
      out.write("					let villageOk = 'N';\r\n");
      out.write("					$(() => {\r\n");
      out.write("						const $siSelect = $('#si');\r\n");
      out.write("						const $guSelect = $('#gu');\r\n");
      out.write("						const $dongSelect = $('#dong');\r\n");
      out.write("				\r\n");
      out.write("						$siSelect.change(() => {\r\n");
      out.write("							const siValue = $siSelect.val();\r\n");
      out.write("							console.log(siValue);\r\n");
      out.write("				\r\n");
      out.write("							if (siValue !== null) {\r\n");
      out.write("								$.ajax({\r\n");
      out.write("									url: 'member/guSelect',\r\n");
      out.write("									type: 'GET',\r\n");
      out.write("									data: { si: siValue },\r\n");
      out.write("									success: response => {\r\n");
      out.write("										console.log(response);\r\n");
      out.write("										$guSelect.empty().append('<option value=\"\">구 선택</option>');\r\n");
      out.write("										response.forEach((a) => {\r\n");
      out.write("											$guSelect.append('<option value=' + a.townCode + '>' + a.townName + '</option>');\r\n");
      out.write("										});\r\n");
      out.write("										$guSelect.prop('disabled', false); // 구 셀렉트 박스 활성화\r\n");
      out.write("									},\r\n");
      out.write("									error: function () {\r\n");
      out.write("										alert('오류임 ㅉㅉ');\r\n");
      out.write("									}\r\n");
      out.write("								});\r\n");
      out.write("							}\r\n");
      out.write("						});\r\n");
      out.write("				\r\n");
      out.write("						$guSelect.change(() => {\r\n");
      out.write("							const guValue = $guSelect.val();\r\n");
      out.write("							console.log(\"선택한구벨류값:\", guValue);\r\n");
      out.write("							if (guValue !== null) {\r\n");
      out.write("								$.ajax({\r\n");
      out.write("									url: 'member/dongSelect',\r\n");
      out.write("									type: 'GET',\r\n");
      out.write("									data: { gu: guValue },\r\n");
      out.write("									success: response => {\r\n");
      out.write("										console.log(response);\r\n");
      out.write("										$dongSelect.empty().append('<option value=\"\">동 선택</option>')\r\n");
      out.write("										response.forEach((a) => {\r\n");
      out.write("											$dongSelect.append('<option value=' + a.villageCode + '>' + a.villageName + '</option>');\r\n");
      out.write("										});\r\n");
      out.write("										$dongSelect.prop('disabled', false); // 동 셀렉트 박스 활성화\r\n");
      out.write("									},\r\n");
      out.write("									error: function () {\r\n");
      out.write("										alert('오류임 키키 ');\r\n");
      out.write("									}\r\n");
      out.write("								});\r\n");
      out.write("				\r\n");
      out.write("								$dongSelect.change(() => {\r\n");
      out.write("									if ($dongSelect.val() !== \"\") {\r\n");
      out.write("										villageOk = 'Y';\r\n");
      out.write("									}\r\n");
      out.write("								}); \r\n");
      out.write("							}\r\n");
      out.write("						});\r\n");
      out.write("					});\r\n");
      out.write("				</script>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group rel\">\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" id=\"postcode\" placeholder=\"우편번호\" name=\"postCode\">\r\n");
      out.write("                    <button class=\"btn btn-outline-secondary\" type=\"button\" id=\"findaddr\">주소검색</button>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" id=\"address1\" placeholder=\"도로명주소\" name=\"addr1\">\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" id=\"address2\" placeholder=\"상세주소\" name=\"addr2\">\r\n");
      out.write("                </div>\r\n");
      out.write("<script>\r\n");
      out.write("    let addrOk = 'N';\r\n");
      out.write("    $(() => {\r\n");
      out.write("        const $findaddr = $('#findaddr');\r\n");
      out.write("        const $postCode = $('#postcode');\r\n");
      out.write("        const $addr1 = $('#address1');\r\n");
      out.write("        const $addr2 = $('#address2');\r\n");
      out.write("\r\n");
      out.write("        $findaddr.click(() => { // 주소찾기 버튼 클릭\r\n");
      out.write("            new daum.Postcode({\r\n");
      out.write("                oncomplete: (result) => {\r\n");
      out.write("                    let addr = '';\r\n");
      out.write("                    let extraAddr = '';\r\n");
      out.write("\r\n");
      out.write("                    if (result.userSelectedType === 'R') { // R은 도로명주소를 선택했을 때 반환되는 값\r\n");
      out.write("                        addr = result.roadAddress;\r\n");
      out.write("                    } else {\r\n");
      out.write("                        addr = result.jibunAddress;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    if (result.userSelectedType === 'R') {\r\n");
      out.write("                        if (result.bname !== '' && /[동|로|가]$/g.test(result.bname)) {\r\n");
      out.write("                            extraAddr += result.bname;\r\n");
      out.write("                        }\r\n");
      out.write("                        if (result.buildingName !== '' && result.apartment === 'Y') {\r\n");
      out.write("                            extraAddr += (extraAddr !== '' ? ', ' + result.buildingName : result.buildingName);\r\n");
      out.write("                        }\r\n");
      out.write("                        if (extraAddr !== '') {\r\n");
      out.write("                            extraAddr = ' (' + extraAddr + ')';\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                    $('#postcode').val(result.zonecode);\r\n");
      out.write("                    $('#address1').val(addr + extraAddr);\r\n");
      out.write("\r\n");
      out.write("                    // 이 부분은 주소가 선택된 후에도 검사\r\n");
      out.write("                }\r\n");
      out.write("            }).open(); // 우편번호 검색창을 여는 것\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        // 페이지 로드 시 값을 검사\r\n");
      out.write("        if ($postCode.val() !== \"\" && $addr1.val() !== \"\" && $addr2.val() !== \"\") {\r\n");
      out.write("            addrOk = 'Y';\r\n");
      out.write("        } else {\r\n");
      out.write("            addrOk = 'N';\r\n");
      out.write("        }\r\n");
      out.write("        console.log('페이지 로드 시 addrOk ',addrOk); // 페이지 로드 시 addrOk 값 출력\r\n");
      out.write("\r\n");
      out.write("        $addr2.blur(() => {\r\n");
      out.write("        	 if ($postCode.val() !== \"\" && $addr1.val() !== \"\" && $addr2.val() !== \"\") {\r\n");
      out.write("                 addrOk = 'Y';\r\n");
      out.write("             } else {\r\n");
      out.write("                 addrOk = 'N';\r\n");
      out.write("             }\r\n");
      out.write("            console.log(addrOk);\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <div class=\"buttonwrap\">\r\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-primary joinbtn\" id=\"joinbtn\" >회원가입</button>\r\n");
      out.write("                    <button type=\"reset\" class=\"btn btn-secondary joinbtn\">초기화</button>\r\n");
      out.write("                </div>\r\n");
      out.write("               <script>\r\n");
      out.write("			               let idOkay = 'N';\r\n");
      out.write("			               let nickOk = 'N';\r\n");
      out.write("						  \r\n");
      out.write("						function ccc(){\r\n");
      out.write("							console.log(\"이거됨?\");\r\n");
      out.write("				        if (idOkay !== 'Y') {\r\n");
      out.write("				            alert(\"아이디 중복 체크를 해주세요.\");\r\n");
      out.write("				           return false;\r\n");
      out.write("				        } else if (pwOk !== 'Y') {\r\n");
      out.write("				            alert(\"비밀번호가 일치하지 않습니다.\");\r\n");
      out.write("				        	return false;\r\n");
      out.write("				        } else if (nameOk !== 'Y') {\r\n");
      out.write("				            alert(\"이름을 확인해주세요.\");\r\n");
      out.write("				        	return false ;\r\n");
      out.write("				        } else if (nickOk !== 'Y') {\r\n");
      out.write("				            alert(\"닉네임 중복 체크를 해주세요.\");\r\n");
      out.write("				        	return false;\r\n");
      out.write("				        } else if (telOk !== 'Y') {\r\n");
      out.write("				            alert(\"핸드폰번호를 확인해주세요.\");\r\n");
      out.write("				        	return false;\r\n");
      out.write("				        }else if (villageOk !=='Y'){\r\n");
      out.write("				        	alert(\"관심지역을 선택해주세요.\");\r\n");
      out.write("				        	return false;\r\n");
      out.write("				        }else if (addrOk !== 'Y') {\r\n");
      out.write("				            alert(\"주소를 확인해주세요.\");\r\n");
      out.write("				        	return false;\r\n");
      out.write("				        }\r\n");
      out.write("				        return true;\r\n");
      out.write("					}\r\n");
      out.write("				</script>\r\n");
      out.write("\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("        <br><br>\r\n");
      out.write("    </div>\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- 모달 \r\n");
      out.write("    <div class=\"modal fade\" id=\"emailModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"emailModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("        <div class=\"modal-dialog modal-md\" role=\"document\">\r\n");
      out.write("            <div class=\"modal-content\">\r\n");
      out.write("                <!-- Modal Header\r\n");
      out.write("                <div class=\"modal-header\">\r\n");
      out.write("                    <h5 class=\"modal-title\" id=\"emailModalLabel\">이메일 인증</h5>\r\n");
      out.write("                    <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("                        <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Modal body \r\n");
      out.write("                <div class=\"modal-body\">\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"authCode\" class=\"mr-sm-2\">인증번호 : </label>\r\n");
      out.write("                        <div class=\"input-group\">\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\" placeholder=\"Enter Auth Code\" id=\"authCode\" name=\"authCode\">\r\n");
      out.write("                            <div class=\"input-group-append\">\r\n");
      out.write("                                <button type=\"button\" class=\"btn btn-primary\" id=\"checkAuthCode\">인증</button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <button type=\"button\" class=\"btn btn-secondary mt-2\" id=\"resendAuthCode\">인증번호 재전송</button>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Modal footer \r\n");
      out.write("                <div class=\"modal-footer\">\r\n");
      out.write("                    <button type=\"button\" class=\"btn btn-secondary\" data-dismiss=\"modal\">닫기</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    -->\r\n");
      out.write("    <script>\r\n");
      out.write("        // 아이디 중복체크\r\n");
      out.write("        $(() => {\r\n");
      out.write("            const $idInput = $('#userId');\r\n");
      out.write("            const pattern = /^[a-z0-9]{5,12}$/; \r\n");
      out.write("            const $checkId = $('#checkId');\r\n");
      out.write("\r\n");
      out.write("            $checkId.click(() => {\r\n");
      out.write("                const userId = $idInput.val();\r\n");
      out.write("                if (!pattern.test(userId)) {\r\n");
      out.write("                    alert(\"아이디는 소문자와 숫자를 포함하여 5~12자여야 합니다.\");\r\n");
      out.write("                    return;\r\n");
      out.write("                }\r\n");
      out.write("                console.log(\"콘솔에 잘 찍힘?:\", userId); \r\n");
      out.write("                $.ajax({\r\n");
      out.write("                    url: 'member/check-id',\r\n");
      out.write("                    type: 'POST',\r\n");
      out.write("                    data: { userId: userId }, \r\n");
      out.write("                    success: response => {\r\n");
      out.write("                        if (response === 'Y') {\r\n");
      out.write("                            alert(\"중복된 아이디 입니다. 다른 아이디를 사용해주세요\");\r\n");
      out.write("                        } else {\r\n");
      out.write("                            alert(\"사용 가능한 아이디 입니다.\");\r\n");
      out.write("                             idOkay ='Y'\r\n");
      out.write("                        }\r\n");
      out.write("                        //console.log(\"아이디오케?\",idOkay);\r\n");
      out.write("                    },\r\n");
      out.write("                    error: function() {\r\n");
      out.write("                        alert('오류 발생');\r\n");
      out.write("                    }\r\n");
      out.write("                  \r\n");
      out.write("                });\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        // 닉네임 유효성 검사후 중복검사\r\n");
      out.write("        $(() => {\r\n");
      out.write("            const $nickInput = $('#nickName');\r\n");
      out.write("            const pattern = /^[가-힣a-zA-Z0-9]{2,10}$/;\r\n");
      out.write("            const $checknick = $('#checkNickName');\r\n");
      out.write("            $checknick.click(() => {\r\n");
      out.write("                const userNick = $nickInput.val();\r\n");
      out.write("                if (!pattern.test(userNick)) {\r\n");
      out.write("                    alert(\"닉네임은 한글/영문/숫자를 이용하여 2~10 자리로 작성해주세요\");\r\n");
      out.write("                    return;\r\n");
      out.write("                }\r\n");
      out.write("                console.log(\"콘솔에 잘 찍힘?:\", userNick);\r\n");
      out.write("                $.ajax({\r\n");
      out.write("                    url: 'member/check-nick',\r\n");
      out.write("                    type: 'POST',\r\n");
      out.write("                    data: { userNick: userNick }, \r\n");
      out.write("                    success: response => {\r\n");
      out.write("                        if (response === 'Y') {\r\n");
      out.write("                            alert(\"중복된 닉네임 입니다. 다른 닉네임을 사용해주세요\");\r\n");
      out.write("                        } else {\r\n");
      out.write("                            alert(\"사용 가능한 닉네임 입니다.\");\r\n");
      out.write("                            nickOk='Y'\r\n");
      out.write("                        }\r\n");
      out.write("                    },\r\n");
      out.write("                    error: function() {\r\n");
      out.write("                        alert('오류 발생');\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("		 \r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
