/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.87
 * Generated at: 2024-07-22 06:47:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class myPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1721298713299L));
    _jspx_dependants.put("jar:file:/D:/seongha/team_project/REDCLIP/redclip/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\" />\r\n");
      out.write("    <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>마이페이지</title>\r\n");
      out.write("<style>\r\n");
      out.write("    .modal-body { line-height: 2rem; }\r\n");
      out.write("\r\n");
      out.write("        body {\r\n");
      out.write("        	width:100%;\r\n");
      out.write("        	height:auto;\r\n");
      out.write("            margin: 20px;\r\n");
      out.write("            line-height: 1.6;\r\n");
      out.write("            height: auto;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .tab {\r\n");
      out.write("            width: 1200px;\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("            margin-top: 50px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        #title {\r\n");
      out.write("        	margin: 30px; \r\n");
      out.write("            margin-left: 340px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("		#content {\r\n");
      out.write("			width:100%;\r\n");
      out.write("			height: auto;\r\n");
      out.write("			margin-bottom: 300px;\r\n");
      out.write("    		margin-top: 100px;\r\n");
      out.write("			}\r\n");
      out.write("       \r\n");
      out.write("        #updateForm {\r\n");
      out.write("             margin: 0 auto; \r\n");
      out.write("             width: 1200px;\r\n");
      out.write("             margin-top: 30px;\r\n");
      out.write("            }\r\n");
      out.write("        \r\n");
      out.write("        #changeName {\r\n");
      out.write("        	width: 100px;\r\n");
      out.write("        	height: 100px;\r\n");
      out.write("        	\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #buttons {\r\n");
      out.write("        	float: right;\r\n");
      out.write("            margin-top: 60px;\r\n");
      out.write("         }\r\n");
      out.write("\r\n");
      out.write("         #delete-btn {\r\n");
      out.write("            margin-top: 80px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        #pointbar {\r\n");
      out.write("        	margin-top: 40px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <header>\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/header.jsp", out, false);
      out.write("\r\n");
      out.write("    </header>\r\n");
      out.write("    <nav style=\"--bs-breadcrumb-divider: '>';\" aria-label=\"breadcrumb\">\r\n");
      out.write("        <ol class=\"breadcrumb\">\r\n");
      out.write("      	<img src=\"/redclip/resources/img/house-door-fill.svg\" style=\"margin-right: 4px\" />\r\n");
      out.write("        <li class=\"breadcrumb-item\"><a href=\"#\">Home</a></li>\r\n");
      out.write("        <li class=\"breadcrumb-item\"><a href=\"#\">마이페이지</a></li>\r\n");
      out.write("        <li class=\"breadcrumb-item active\" aria-current=\"page\">회원정보 수정</li>\r\n");
      out.write("        </ol>\r\n");
      out.write("    </nav>\r\n");
      out.write("    <!-- 탭 클릭 시 비동기식 요청으로 화면 전환 -->\r\n");
      out.write("    <div class=\"tab\">\r\n");
      out.write("        <ul class=\"nav nav-tabs\">\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link active\" aria-current=\"page\" href=\"#\">내 정보</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/blockList/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ sessionScope.loginUser.userId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">차단 목록</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link\"  href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/myProduct/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ sessionScope.loginUser.userId  }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">내가 쓴 글</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/wishList/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ sessionScope.loginUser.userId  }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">찜한 상품</a>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"content\">\r\n");
      out.write("    \r\n");
      out.write("    <h3 id=\"title\">회원정보 수정</h3>\r\n");
      out.write("    \r\n");
      out.write("        <div id=\"updateForm\">\r\n");
      out.write("            <div>\r\n");
      out.write("                <div class=\"userImg\">\r\n");
      out.write("                	<div id=\"profil\">\r\n");
      out.write("						<img alt=\"프로필 사진\" src=\"\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<input type=\"file\" id=\"inputGroupFile04\" aria-describedby=\"inputGroupFileAddon04\" aria-label=\"Upload\">\r\n");
      out.write("				</div>\r\n");
      out.write("                    \r\n");
      out.write("                    <label for=\"userId\">* ID </label><br>\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ sessionScope.loginUser.userId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" id=\"userId\"  neme=\"userId\" aria-label=\"Disabled input example\" disabled readonly> <br>\r\n");
      out.write("                    \r\n");
      out.write("                    <input type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ sessionScope.loginUser.userPwd }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" id=\"userPwd\"  neme=\"userPwd\"> <br>\r\n");
      out.write("\r\n");
      out.write("                    <label for=\"userName\">* Name : </label>\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" id=\"userName\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ sessionScope.loginUser.userName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"userName\" required> <br>\r\n");
      out.write("\r\n");
      out.write("                    <label for=\"nickname\">* Nickname : </label>\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" id=\"nickname\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ sessionScope.loginUser.nickname }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"nickname\" required> <br>\r\n");
      out.write("\r\n");
      out.write("                    <label for=\"email\"> &nbsp; Email : </label>\r\n");
      out.write("                    <input type=\"email\" class=\"form-control\" id=\"email\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ sessionScope.loginUser.email }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"email\"> <br>\r\n");
      out.write("\r\n");
      out.write("                    <label for=\"tel\"> &nbsp; Tel : </label>\r\n");
      out.write("                    <input type=\"tel\" class=\"form-control\" id=\"tel\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ sessionScope.loginUser.tel }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"tel\"> <br>\r\n");
      out.write("\r\n");
      out.write("                    <label for=\"postCode\"> &nbsp; PostCode : </label>\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" id=\"postCode\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ sessionScope.loginUser.postCode }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"postCode\"> <br>\r\n");
      out.write("                    \r\n");
      out.write("                    <label for=\"address\"> &nbsp; Address : </label>\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" id=\"address\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ sessionScope.loginUser.address }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"address\">\r\n");
      out.write("                    \r\n");
      out.write("                    <label for=\"villageCode\"> &nbsp; VillageCode : </label>\r\n");
      out.write("                    <input type=\"number\" class=\"form-control\" id=\"villageCode\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ sessionScope.loginUser.villageCode }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"villageCode\">\r\n");
      out.write("\r\n");
      out.write("                    <!-- 자스 사용 -> aria-valuenow 값에 따라 progress-bar에 style 주기 -->\r\n");
      out.write("                    <div id=\"pointbar\">다음 등급까지\r\n");
      out.write("	                    <div class=\"progress\"  id=\"progress\" role=\"progressbar\" aria-label=\"Basic example\" aria-valuenow=\"0\" aria-valuemin=\"0\" aria-valuemax=\"100\" >\r\n");
      out.write("	                        <div class=\"progress-bar\" style=\"width: 0%\"></div>\r\n");
      out.write("	                    </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("               \r\n");
      out.write("				<div id=\"buttons\">\r\n");
      out.write("                    <button type=\"button\" id=\"userUpdate\" class=\"btn btn-success\" onclick=\"update();\">수정</button>\r\n");
      out.write("                    <button type=\"reset\" class=\"btn btn-secondary\" onclick=\"location.reloard\">취소</button><br>\r\n");
      out.write("                    <button type=\"button\" id=\"delete-btn\" class=\"btn btn-secondary\" data-toggle=\"modal\" data-target=\"#deleteForm\">회원탈퇴</button>\r\n");
      out.write("				</div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("	<footer>\r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/footer.jsp", out, false);
      out.write("\r\n");
      out.write("    </footer>\r\n");
      out.write("    \r\n");
      out.write("    <!--회원 탈퇴 시 띄워줄 모달창 -->\r\n");
      out.write("    <div class=\"modal fade\" id=\"deleteForm\">\r\n");
      out.write("        <div class=\"modal-dialog modal-lg\">\r\n");
      out.write("            <div class=\"modal-content\">\r\n");
      out.write("\r\n");
      out.write("                <!-- Modal Header -->\r\n");
      out.write("                <div class=\"modal-header\">\r\n");
      out.write("                    <h4 class=\"modal-title\">회원탈퇴</h4>\r\n");
      out.write("                    <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div>\r\n");
      out.write("                	<!-- 같은 조건의 pwd 값을 가진 모든 유저가 삭제 될 수 있으므로 행을 식별할 수 있는 값을 추가 -->\r\n");
      out.write("                	<input type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ sessionScope.loginUser.userId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" id=\"loginUserId\" name=\"userId\">\r\n");
      out.write("                    <!-- Modal body -->\r\n");
      out.write("                    <div class=\"modal-body\">\r\n");
      out.write("                        <div align=\"left\">\r\n");
      out.write("                            회원 정보 삭제<br><br>\r\n");
      out.write("                            \r\n");
      out.write("                            회원 탈퇴와 함께 RED CRIP 에 등록된 모든 개인정보는 삭제, 폐기 처리되며 복구되지 않습니다.<br>\r\n");
      out.write("                            \r\n");
      out.write("                            단, 상법 및 '전자상거래 등에서 소비자 보호에 관한 법률' 등 관련 법령의 규정에 의하여 다음과 같이 ‘거래 관련 관리의무 관계 확인’ 등을 이유로 일정 기간 보관됩니다.<br>\r\n");
      out.write("                             - 거래에 관한 기록 : 5년<br>\r\n");
      out.write("                             - 소비자의 불만 또는 분쟁 처리에 관한 기록 : 3년<br>\r\n");
      out.write("                             - 설문조사, 이벤트 등 일시적 목적을 위하여 수집한 경우 : 당해 설문조사, 이벤트 등의 종료 시까지<br>\r\n");
      out.write("                            \r\n");
      out.write("                            회원 탈퇴와 함께 RED CRIP 에 등록된 모든 개인정보가 삭제됨에 따라 point 역시 함께 소멸됩니다.<br><br><br>\r\n");
      out.write("\r\n");
      out.write("                            <strong>※ 탈퇴 시 회원님의 RED CRIP 이용정보가 삭제되며 복구가 불가능하오니 신중히 선택하시기 바랍니다.</strong><br>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-check\">\r\n");
      out.write("                            <input class=\"form-check-input\" type=\"checkbox\" value=\"\" id=\"flexCheckDefault\">\r\n");
      out.write("                            <label class=\"form-check-label\" for=\"flexCheckDefault\">\r\n");
      out.write("                              모든 내용을 숙지하였으며 회원 탈퇴에 동의합니다.\r\n");
      out.write("                            </label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Modal footer -->\r\n");
      out.write("                    <div class=\"modal-footer\" align=\"center\">\r\n");
      out.write("                    	<button type=\"button\" id=\"delete\" class=\"btn btn-secondary\" onclick=\"changeStatus();\">탈퇴하기</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("   <script>\r\n");
      out.write("	\r\n");
      out.write("     	//회원정보 수정\r\n");
      out.write("   		function update() {\r\n");
      out.write("   			\r\n");
      out.write("   			var updateData = {\r\n");
      out.write("   					\"userId\" : $('#userId').val(),\r\n");
      out.write("   					\"userName\" : $('#userName').val(),\r\n");
      out.write("   					\"nickname\" : $('#nickname').val(),\r\n");
      out.write("   					\"email\" : $('#email').val(),\r\n");
      out.write("   					\"tel\" : $('#tel').val(),\r\n");
      out.write("   					\"postCode\" : $('#postCode').val(),\r\n");
      out.write("   					\"address\" : $('#address').val(),\r\n");
      out.write("   					\"villageCode\" : $('#villageCode').val()\r\n");
      out.write("   					\r\n");
      out.write("   			};\r\n");
      out.write("   			\r\n");
      out.write("   			 //console.log(updateData);\r\n");
      out.write("\r\n");
      out.write("   			$.ajax({\r\n");
      out.write("   				url : 'member/',\r\n");
      out.write("   				type : 'put',\r\n");
      out.write("   				data : JSON.stringify(updateData),\r\n");
      out.write("   				contentType : 'application/json',\r\n");
      out.write("   				success : function(result) {\r\n");
      out.write("   					\r\n");
      out.write("   					//console.log(result);\r\n");
      out.write("   					\r\n");
      out.write("   						alert('회원 정보가 수정되었습니다.');\r\n");
      out.write("   						\r\n");
      out.write("   					},\r\n");
      out.write("   				error : function(error) {\r\n");
      out.write("   					alert('회원 정보 수정에 실패했습니다.');\r\n");
      out.write("   				}\r\n");
      out.write("   			});\r\n");
      out.write("   		};\r\n");
      out.write("   		\r\n");
      out.write("   		//프로필 사진 업데이트\r\n");
      out.write("\r\n");
      out.write("   		//체크박스 체크 여부 확인(시간 남으면 구현)\r\n");
      out.write("   		//프로필 이미지 사진 바뀌면 미리 보이는 기능(시간 남으면 구현)\r\n");
      out.write("   		\r\n");
      out.write("   		\r\n");
      out.write("   		//회원 탈퇴\r\n");
      out.write("   		function changeStatus() {\r\n");
      out.write("   			\r\n");
      out.write("   			const userId = $('#loginUserId').val();\r\n");
      out.write("   			\r\n");
      out.write("   			//console.log(userId);\r\n");
      out.write("   			\r\n");
      out.write("   			$.ajax({\r\n");
      out.write("   				url: 'member/' + userId,\r\n");
      out.write("   				type: 'put',\r\n");
      out.write("   				success : result => {\r\n");
      out.write("   					\r\n");
      out.write("   					alert('회원 탈퇴에 성공했습니다.');\r\n");
      out.write("   					location.reload();\r\n");
      out.write("   				},\r\n");
      out.write("   				error : (e) => {\r\n");
      out.write("   					\r\n");
      out.write("   					//console.log(\"요청 실패\");\r\n");
      out.write("   					alert('회원 탈퇴에 실패했습니다.');\r\n");
      out.write("   				}\r\n");
      out.write("   			});\r\n");
      out.write("   			\r\n");
      out.write("   		};\r\n");
      out.write("   		\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
